### ISSUE TITLE
Configmanager release please

### ISSUE THREAD

**Issue by haizaar** [jbasko/strictus#1]
Hi Jazeps,

Sorry for opening unrelated issue, but I have no other means to reach out.

I see you have archived the repo, but I'd really like to have a small update pushed:
https://github.com/haizaar/configmanager/commit/e79ad6fc83ed82126151b940d04f4f47703b1f18.  Otherwise annoying warning is produced every time.

Is it possible for you to un-archive it and roll out another release?
If you are too busy, may be you can give me access to this package on PyPI and I'll do it myself (username: haizaar).

Thank you kindly,
Zaar

**Comment by jbasko** [comment]
Done. I will delete this issue now. My email is jazeps.basko@gmail.com
